/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * MapUnlockedPanel.java
 *
 * Created on 29.08.2011, 10:41:43
 */
package de.cismet.cismap.commons.gui.statusbar;

/**
 * DOCUMENT ME!
 *
 * @author   jweintraut
 * @version  $Revision$, $Date$
 */
public class MapExtentUnfixedPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler gluFiller;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form MapUnlockedPanel.
     */
    public MapExtentUnfixedPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        gluFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(16, 16),
                new java.awt.Dimension(32767, 32767));

        setLayout(new java.awt.BorderLayout());
        add(gluFiller, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents
}
