/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * ServicesErrorPanel.java
 *
 * Created on 26.08.2011, 09:40:09
 */
package de.cismet.cismap.commons.gui.statusbar;

/**
 * DOCUMENT ME!
 *
 * @author   jweintraut
 * @version  $Revision$, $Date$
 */
public class ServicesErrorPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblErrorIcon;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ServicesErrorPanel.
     */
    public ServicesErrorPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblErrorIcon = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblErrorIcon.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/cismap/commons/gui/statusbar/error.png"))); // NOI18N
        lblErrorIcon.setText(org.openide.util.NbBundle.getMessage(
                ServicesErrorPanel.class,
                "ServicesErrorPanel.lblErrorIcon.text"));                                      // NOI18N
        lblErrorIcon.setToolTipText(org.openide.util.NbBundle.getMessage(
                ServicesErrorPanel.class,
                "ServicesErrorPanel.lblErrorIcon.toolTipText"));                               // NOI18N
        add(lblErrorIcon, java.awt.BorderLayout.CENTER);
    }                                                                                          // </editor-fold>//GEN-END:initComponents
}
