/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * ServicesRetrievedPanel.java
 *
 * Created on 26.08.2011, 09:41:08
 */
package de.cismet.cismap.commons.gui.statusbar;

/**
 * DOCUMENT ME!
 *
 * @author   jweintraut
 * @version  $Revision$, $Date$
 */
public class ServicesRetrievedPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblServicesRetrievedIcon;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ServicesRetrievedPanel.
     */
    public ServicesRetrievedPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblServicesRetrievedIcon = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblServicesRetrievedIcon.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/cismap/commons/gui/statusbar/ok.png"))); // NOI18N
        lblServicesRetrievedIcon.setText(org.openide.util.NbBundle.getMessage(
                ServicesRetrievedPanel.class,
                "ServicesRetrievedPanel.lblServicesRetrievedIcon.text"));                   // NOI18N
        lblServicesRetrievedIcon.setToolTipText(org.openide.util.NbBundle.getMessage(
                ServicesRetrievedPanel.class,
                "ServicesRetrievedPanel.lblServicesRetrievedIcon.toolTipText"));            // NOI18N
        add(lblServicesRetrievedIcon, java.awt.BorderLayout.CENTER);
    }                                                                                       // </editor-fold>//GEN-END:initComponents
}
