/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cismap.commons;

/**
 * This calss can be used to remove time consuming debug messages from generated bytecode.
 *
 * @author   Pascal Dihé
 * @version  $Revision$, $Date$
 */
public class Debug {

    //~ Static fields/initializers ---------------------------------------------

    /** Set to {@code false} to remove all debug statements during compiling. */
    public static final boolean DEBUG = true;
}
