package de.cismet.cismap.commons.gui.piccolo;

import edu.umd.cs.piccolo.PNode;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import pswing.PSwing;

/**
 *
 */
public class MeasurementPanel extends JPanel {

    private ImageIcon icoRuler = new ImageIcon(getClass().getResource("/de/cismet/cismap/commons/gui/res/ruler-triangle.png"));//NOI18N

    private final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());
    private PFeature pfeature;
    private PNode pNodeParent;
    private PSwing pSwing;
    private static final Color COLOR_BORDER = new Color(0, 0, 0);
    private static final Color COLOR_BACKGROUND = new Color(210, 210, 210);

    /** Creates new form InfoPanel */
    public MeasurementPanel() {
        super();
        try {
            initComponents();
        } catch (Throwable t) {
            log.error("Error in InfoPanel", t);//NOI18N
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblLength = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblLength.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.Desktop.background"));
        lblLength.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLength.setIcon(icoRuler);
        lblLength.setText(org.openide.util.NbBundle.getMessage(MeasurementPanel.class, "InfoPanel.jLabel1.text")); // NOI18N
        lblLength.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLengthMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 4);
        add(lblLength, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLengthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLengthMouseClicked

}//GEN-LAST:event_lblLengthMouseClicked

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        g.setColor(COLOR_BACKGROUND);
        g.fillRoundRect(2, 1, getWidth() - 4, getHeight() - 2, 10, 10);
        g.setColor(COLOR_BORDER);
        g.drawRoundRect(2, 1, getWidth() - 4, getHeight() - 2, 10, 10);

        if (pNodeParent != null) {
            pNodeParent.setWidth(getWidth());
            pNodeParent.setHeight(getHeight());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLength;
    // End of variables declaration//GEN-END:variables

    public void setLengthInfo(String text) {
        lblLength.setText(text);
        revalidate();
        repaint();
    }

    public PFeature getPfeature() {
        return pfeature;
    }

    public void setPfeature(PFeature pfeature) {
        this.pfeature = pfeature;
    }

    public PNode getPNodeParent() {
        return pNodeParent;
    }

    public void setPNodeParent(PNode pNodeParent) {
        this.pNodeParent = pNodeParent;
    }

    public PSwing getPSwing() {
        return pSwing;
    }

    public void setPSwing(PSwing pSwing) {
        this.pSwing = pSwing;
    }
}
